### ISSUE TITLE
Application API Demo Error on Heroku 

### ISSUE THREAD

**Issue by gaetan1903** [nandakishormpai/Plant_Disease_Detector#2]
```
import requests
url = "https://plant-disease-detector-pytorch.herokuapp.com/"
#imgdata = base64 string of image
r = requests.post(url,json = {"image":imgdata})
print(r.text.strip())
``` 

'<!DOCTYPE html>\n\t<html>\n\t  <head>\n\t\t<meta name="viewport" content="width=device-width, initial-scale=1">\n\t\t<meta charset="utf-8">\n\t\t<title>Application Error</title>\n\t\t<style media="screen">\n\t\t  html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t  }\n\t\t  html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t  }\n\t\t  iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t  }\n\t\t</style>\n\t  </head>\n\t  <body>\n\t\t<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>\n\t  </body>\n\t</html>'

**Comment by nandakishormpai** [comment]
Thank you, Gaetan for raising the issue. There was some issue from the deployment side with Heroku and flask and it has been fixed. I hope you can get results if you try accessing the API with the base64 string of the image as imgdata. Let me know if there are any more issues. Thanks a lot for bringing this to my attention and sorry for the late reply.
